In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

In [2]:
# zfc.py       root module
# knots.py     strings
# scholar.py   read/write
# rng.py       RNG
# woodcut.py   printing

In [3]:
from pyscripts.zfc import seq

In [4]:
seq(1, 5)

array([1, 2, 3, 4, 5])

In [5]:
seq(1, 5, incl=False)

array([1, 2, 3, 4])

In [6]:
seq(1, 5.1)

array([1, 2, 3, 4, 5])

In [7]:
seq(1.1, 5)

array([ 1.1,  2.1,  3.1,  4.1])

In [8]:
seq(1, 5, step=1.1)

array([ 1. ,  2.1,  3.2,  4.3])

In [9]:
from pyscripts.zfc import weave

In [10]:
a = seq(1,6)
b = seq(100,97)

In [11]:
weave(a,b)

array([1, 100, 2, 99, 3, 98, 4, 97, 5, 6], dtype=object)

In [12]:
weave(b,a)

array([100, 1, 99, 2, 98, 3, 97, 4, 5, 6], dtype=object)

In [13]:
from pyscripts.knots import chr_codes

In [14]:
chr_codes('abc')

array([97, 98, 99])

In [15]:
chr_codes('ABC')

array([65, 66, 67])

In [16]:
chr_codes('123')

array([49, 50, 51])

In [17]:
from pyscripts.knots import extract_ext, strip_ext

In [18]:
strip_ext('config.txt')

'config'

In [19]:
extract_ext('config.txt')

'txt'

In [20]:
from pyscripts.knots import os_path

In [21]:
os_path('c:\\program files//Git\/\cmd')

'c:\\program files\\Git\\cmd'

In [22]:
from pyscripts.knots import str_replace

In [23]:
str_replace('the quick brown fox jumps over the lazy dog.', replace_these=['a','b','c','the'], with_this='?')

'? qui?k ?rown fox jumps over ? l?zy dog.'

In [24]:
from pyscripts.scholar import dir_apply

In [25]:
dir_apply(os_path('c:/git/pyscripts'),
          folder_filter = lambda x: x not in ['.git', '.idea', '__pycache__'],
          file_filter = lambda x: x.endswith('.txt'))

array(['c:\\git\\pyscripts\\hierarchy.txt',
       'c:\\git\\pyscripts\\LICENSE.txt',
       'c:\\git\\pyscripts\\requirements.txt',
       'c:\\git\\pyscripts\\licenses\\my_license.txt',
       'c:\\git\\pyscripts\\licenses\\stackoverflow.txt',
       'c:\\git\\pyscripts\\licenses\\matplotlib\\LICENSE_enthought.txt',
       'c:\\git\\pyscripts\\licenses\\matplotlib\\Solarized.txt',
       'c:\\git\\pyscripts\\licenses\\numpy\\LICENSE.txt',
       'c:\\git\\pyscripts\\licenses\\randomstate\\PCG-LICENSE.txt',
       'c:\\git\\pyscripts\\licenses\\randomstate\\RANDOMKIT-LICENSE.txt',
       'c:\\git\\pyscripts\\licenses\\scipy\\LICENSE.txt'], dtype=object)

In [26]:
dir_apply(os_path('c:/git/pyscripts'),
          file_filter = lambda x: x.endswith('.py'))

array(['c:\\git\\pyscripts\\pyscripts\\bamboo.py',
       'c:\\git\\pyscripts\\pyscripts\\commune.py',
       'c:\\git\\pyscripts\\pyscripts\\henshin.py',
       'c:\\git\\pyscripts\\pyscripts\\hero.py',
       'c:\\git\\pyscripts\\pyscripts\\kaggle.py',
       'c:\\git\\pyscripts\\pyscripts\\knots.py',
       'c:\\git\\pyscripts\\pyscripts\\mytypes.py',
       'c:\\git\\pyscripts\\pyscripts\\rng.py',
       'c:\\git\\pyscripts\\pyscripts\\scholar.py',
       'c:\\git\\pyscripts\\pyscripts\\scripts.py',
       'c:\\git\\pyscripts\\pyscripts\\viz.py',
       'c:\\git\\pyscripts\\pyscripts\\woodcut.py',
       'c:\\git\\pyscripts\\pyscripts\\zfc.py',
       'c:\\git\\pyscripts\\pyscripts\\__init__.py'], dtype=object)

In [27]:
from pyscripts.rng import roll

In [28]:
roll('3d6')

(11, array([2, 4, 5]))

In [29]:
roll('3d6')

(7, array([5, 1, 1]))

In [30]:
roll('3d6')

(9, array([5, 2, 2]))

In [31]:
from pyscripts.rng import r_ints, r_chrs, r_strings

In [32]:
r_ints(10, 1, 100)

array([46, 37, 84, 10, 24, 93, 79, 59,  3, 67])

In [33]:
r_chrs(5)

array(['Q', 'Q', 'C', 'P', 'M'], dtype=object)

In [34]:
r_strings(5)

array(['0P376VP', 'OGjEGnf4', 'lUaHu', 'jAcmV', '5sVvk97n'], dtype=object)

In [35]:
r_strings(5, str_format = 'Aa6')

array(['Ot0', 'Dq2', 'Et6', 'Ai1', 'Xb6'], dtype=object)

In [36]:
from pyscripts.rng import permute, bootstrap

In [37]:
x = seq(1,10)

In [38]:
permute(x)

array([ 6,  8,  3,  4,  7,  1,  2,  5, 10,  9])

In [39]:
bootstrap(x)

array([ 4,  6,  4,  3,  7, 10,  5,  4, 10,  6])

In [40]:
from pyscripts.woodcut import printf

In [41]:
printf('ABC')
printf('def')
printf('000')

ABCdef000

In [42]:
from pyscripts.woodcut import print_raw

In [43]:
x = r_chrs(10 * 150).reshape(10,150)

In [44]:
print_raw(x)

WRVIEEXTJKKDRJIUVDSEUBRRWXESJHCGPNAJTHTJBQIHAHIIAQFDLGJGBMENBIMIPQLHIGZRETLIRTQWAGBIUFDQSNAEWGSVTJHGIXGSZBQQTUZWLUBUPCWDENQHVYIPVLWICQVOYQPTFFXJCZPYXV
BBJWEGDEZUVBEEOHULCECOJNAACNOTMOJREUXYNZYOOLWGHJZCTTWJUGUTYOQEHHRQDOQQNDPKPUDCAAZJHUSYMVKTPOICBDOHHPYXYBCUJLYTVYJHMBZJKHVDGPFSFWBOZHJJUFZIOXAKJRWDJHQF
QQNWQVPLVBOYUXSNTLIKIDEYMXOVQAFZZAKVBLGXSHAPFLCIHDAPAGYVZXUNXPXXMSMFJYPRKVLPZOLSNLMCBXLKSONADVFLGCDRTSKJXCWYPXWNHUVEHSVTSWHOHJQOSAKPVVIIVUZJPWRTJRJTLQ
NMFGGHVUJJVRRISTAUHZRQJJLJNOAKCIKEXQVRSFRKZCSQAGTVKTJWGWTSBUFQUCWLHBMLBLNATERLLFSYQMGLHBZVBBBCNLOSZMEHXROPCHOTDAWMBGLCREZTRNFTGMVGVMEPGQNDMEFLYOECIFRH
EQYHSPNBJLRAJVPCAWVGCHJRIJVKUKXNEFIRVKHXFFPIEFLEASJZAZULKEQDPQKOVKEJHNGFROUGHKLAHURJOYRHZNEYNWATFDHEWTQLTRHFCGQVPSSKYTSJSOVGFWVWSHYGORDEOWNJOCYZJJJBMC
PKSOAQMDCIPBDNKMNGSUMBEEVLHUAJVHQQIPRNYCFYRDLIFAXLMWGVIZEBQJOXNMVZSUGJQVLPYHYZABOCXROKODDFIKEKADAJJVBNYCTGGWYQVXCDZIYMARFNNOXOJLOZYFGBIAZBWZVBICPOXTVF
CTZVQNIKTMWDDHUAIEKYJXFPATWNQGWOICWLSVQYUYVYVQLCDUTLUCUZHNWETLCQHSFDJFBLATYBXREPSLFBJPHRQYWTNI

In [45]:
from pyscripts.woodcut import print_arr
from pyscripts.zfc import numpy_vstack

In [46]:
a = r_strings(10)
b = r_ints(10, 1,100) / r_ints(10, 1,10)
c = seq(1,10)

In [47]:
x = numpy_vstack(a,b,c).T

In [48]:
print_arr(x, n_decimals = 3, col_aligns = '< > >')

8VxZ4p36   77.0      1
bKA4Pdb     7.375    2
Y2D9Pxb     2.285    3
2c7yaYsu    5.1      4
036RA      13.285    5
ABV5nb     15.0      6
h63ITo7H    3.833    7
2Kyg98      7.3      8
0uTSVwf    12.666    9
nu4TiL     22.0     10



In [49]:
from pyscripts.woodcut import print_pairtable
from pyscripts.zfc import triangle_num, triangle_num_inv

In [50]:
n = 5

In [51]:
triangle_num(n)

15

In [52]:
x = r_ints(15)

In [53]:
print_pairtable(x, names=seq(1,n))

     1   2    3    4    5
1   10   8   10   -7   -5
2    .   9   -9   10    5
3    .   .    8    2   -6
4    .   .    .    1   -1
5    .   .    .    .   -6

